# Page settings

baseurl = "https://ryo-utsunomiya.github.io/"
languageCode = "en-us"
title = "Resume - Ryo Utsunomiya"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Ryo Utsunomiya"
        tagline = "Software Engineer"
        avatar = "photo.jpeg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: millionsnowliving+githubio@gmail.com"
        title = "millionsnowliving+githubio@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+819082803521"
        title = "+819082803521"

        [[params.contact.list]]
        # class = "wordpress.org"
        # icon = "fa-globe"
        # url = "//profiles.wordpress.org/ryo511"
        # title = "wordpress.org"

        # [[params.contact.list]]
        # class = "linkedin"
        # icon = "fa-linkedin"
        # url = "//linkedin.com/in/johndoe"
        # title = "linkedin.com/in/johndoe"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/ryo-utsunomiya"
        title = "github.com/ryo-utsunomiya"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/ryo511"
        title = "@ryo511"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Dropout"
        college = "University of Tokyo"
        dates = "2005 - 2008"

        [[params.education.list]]
        degree = "High School Graduate"
        college = "Uwajima Higashi High School"
        dates = "2000 - 2003"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Japanese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Business"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I am a Software Engineer based in Tokyo, Japan. I developed many web applications with rich user interfaces and robust architectures. My passion is to write useful, simple and maintainable software. Currently, I'm interested in web site performance and microservices."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Frontend Engineer"
        dates = "2017 - Present"
        company = "Ikyu, Tokyo"
        details = "Built new frontend infrastracture with Vue.js, developed mobile friendly UIs, and increased customer engagements. Optimzied web site performance up to 2x."

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "2013 - 2016"
        company = "Asial, Tokyo"
        details = "Developed many web applications with PHP and JavaScript. Created RESTful APIs and Single Page Applications."

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "2012 - 2013"
        company = "Adglobe, Tokyo"
        details = "Developed a web-based game with PHP, JavaScript and Flash."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Publications"
        intro = "My presentation slides and recent blog posts (in Japanese)"

        [[params.projects.list]]
        title = "slides.com"
        url = "https://slides.com/ryoutsunomiya/"
        tagline = "My presentation slides about web site performance and WordPress related topics."

        [[params.projects.list]]
        title = "一休.com Developers Blog"
        url = "hhttps://user-first.ikyu.co.jp/search?q=ryo-utsunomiya"
        tagline = "My recent blog posts about web site performance and frontend architecture."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        # Languages

        [[params.skills.list]]
        skill = "HTML5"
        level = "100%"

        [[params.skills.list]]
        skill = "CSS3"
        level = "90%"

        [[params.skills.list]]
        skill = "JavaScript"
        level = "100%"

        [[params.skills.list]]
        skill = "TypeScript"
        level = "80%"

        [[params.skills.list]]
        skill = "PHP"
        level = "100%"

        [[params.skills.list]]
        skill = "C#"
        level = "90%"

        [[params.skills.list]]
        skill = "Go"
        level = "70%"

        [[params.skills.list]]
        skill = "SQL"
        level = "90%"

        # Libraries

        [[params.skills.list]]
        skill = "React"
        level = "80%"

        [[params.skills.list]]
        skill = "Vue.js"
        level = "100%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Ryo Utsunomiya"
