# Page settings

baseurl = "https://ryo-utsunomiya.github.io/"
languageCode = "en-us"
title = "Ryo Utsunomiya Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Ryo Utsunomiya"
        tagline = "Software Engineer"
        avatar = "https://ja.gravatar.com/userimage/37823746/62fa022dde4718fca518e8b62d93a919.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: millionsnowliving+githubio@gmail.com"
        title = "millionsnowliving+githubio@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+819082803521"
        title = "+819082803521"

        # [[params.contact.list]]
        # class = "website"
        # icon = "fa-globe"
        # url = "//portfoliosite.com"
        # title = "portfoliosite.com"

        # [[params.contact.list]]
        # class = "linkedin"
        # icon = "fa-linkedin"
        # url = "//linkedin.com/in/johndoe"
        # title = "linkedin.com/in/johndoe"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/ryo-utsunomiya"
        title = "github.com/ryo-utsunomiya"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/ryo511"
        title = "@ryo511"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Not graduated"
        college = "University of Tokyo"
        dates = "2005 - 2008"

        [[params.education.list]]
        degree = "High School Graduate"
        college = "Uwajima Higashi High School"
        dates = "2000 - 2003"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Japanese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I am a Software Engineer based in Tokyo, Japan. I developed several web applications with rich user inteface and robust architecture. My passion is to write simple, clean and maintainable software."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Frontend Engineer"
        dates = "2017 - Present"
        company = "Ikyu, Tokyo"
        details = ""

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "2013 - 2016"
        company = "Asial, Tokyo"
        details = ""

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "2012 - 2013"
        company = "Adglobe, Tokyo"
        details = ""

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "My side projects are below:"

        [[params.projects.list]]
        title = "Gutenberg Meetup"
        url = ""
        tagline = "A meetup specialized on Gutenberg."

        [[params.projects.list]]
        title = "Amazon Block"
        url = ""
        tagline = "A WordPress plugin for Gutenberg editor."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        # Languages

        [[params.skills.list]]
        skill = "HTML5"
        level = "100%"

        [[params.skills.list]]
        skill = "CSS3"
        level = "90%"

        [[params.skills.list]]
        skill = "JavaScript(ES.Next)"
        level = "100%"

        [[params.skills.list]]
        skill = "PHP"
        level = "100%"

        [[params.skills.list]]
        skill = "C#"
        level = "90%"

        [[params.skills.list]]
        skill = "SQL"
        level = "90%"

        # Libraries

        [[params.skills.list]]
        skill = "React"
        level = "80%"

        [[params.skills.list]]
        skill = "Vue.js"
        level = "100%"

        [[params.skills.list]]
        skill = "WordPress"
        level = "80%"

        [[params.skills.list]]
        skill = "Symfony"
        level = "90%"

        [[params.skills.list]]
        skill = "Laravel"
        level = "80%"

        [[params.skills.list]]
        skill = "Linux"
        level = "80%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Ryo Utsunomiya"
